
---
title: "Final Project - Song Repetitiveness"
author: "Eva, Julia, Sophie and Tessa"
output: word_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(stringr)
library(tidytext)
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
```

## Country Data
```{r, warning=FALSE, eval=FALSE}

#Sophies#####
#Use URLs to get song titles, artists, and dates
urlfunction <- function(year) {
  if (year == 1958 || (year >= 2012 && year <= 2023)) {
      country_url <- paste0("https://en.wikipedia.org/wiki/List_of_Billboard_number-one_country_songs_of_",  year)
      html <- read_html(country_url)
      cast <- html_nodes(html, "td:nth-child(3) .fn a , th+ td > a")
  }else if (year >= 1959 && year <= 1961){
      country_url <- paste0("https://en.wikipedia.org/wiki/List_of_Hot_C%26W_Sides_number_ones_of_",  year)
      html <- read_html(country_url)
      cast <- html_nodes(html, ".jquery-tablesorter span a , .jquery-tablesorter th a")
  }else if (year >= 1962 && year <= 1989) {
      country_url <- paste0("https://en.wikipedia.org/wiki/List_of_Hot_Country_Singles_number_ones_of_",  year)
      html <- read_html(country_url)
      cast <- html_nodes(html, ".fn a , td > a")
  }else if (year >= 1990 && year <= 2004) {
      country_url <- paste0("https://en.wikipedia.org/wiki/List_of_Hot_Country_Singles_%26_Tracks_number_ones_of_",  year)
      html <- read_html(country_url)
      cast <- html_nodes(html, ".jquery-tablesorter th+ td a , .jquery-tablesorter th a")
  }else { 
    country_url <- paste0("https://en.wikipedia.org/wiki/List_of_Hot_Country_Songs_number_ones_of_",  year)
    html <- read_html(country_url)
    cast <- html_nodes(html, ".jquery-tablesorter th+ td a , .jquery-tablesorter th a")
  }  

  html_text(cast, trim = TRUE) 
  tables <- html_table(html, fill = TRUE, header = TRUE)
  desired_table <- tables[[1]]
  desired_table <- desired_table[, c(2, 3)]
    #include only the second and third columns which are title and artist
  if ("Title" %in% desired_table[1, ]) {
    desired_table <- desired_table[-1, ]
    #get rid of top row if they have an extra header row
          }
  colnames(desired_table) <- c("Title", "Artist")
    #name columns
  desired_table$Year <- year
     #add columns for year
  desired_table$genre <- "Country" 
     #add column for genre
  desired_table <- unique(desired_table)
    #get rid of repeat columns
  return(desired_table)
      
}
TopSongs <- data.frame()
for(year in 1958:2023){
    current_year <- urlfunction(year)
    TopSongs <- rbind(TopSongs, current_year)
}



#Julia#####

#remove slash and everything behind it
TopSongs$Title<-gsub("/.*", "", TopSongs$Title)

#remove quotation marks
TopSongs$Title<-gsub('"', '', TopSongs$Title)

#new data frame with dashes instead of spaces for url purposes
TopSongs2 <- sapply(TopSongs, function(x) gsub(" ", "-", x))



#EVA####
# Modify artist and title names
TopSongs2 <- as.data.frame(TopSongs2)
TopSongs2$Title <- sub("-$", "", TopSongs2$Title)
TopSongs2$Title <- gsub("[,.?%()]", "", TopSongs2$Title)
TopSongs2$Artist <- gsub("[.']", "", TopSongs2$Artist)
TopSongs2$Artist <- sub("-and", "", TopSongs2$Artist)

```

```{r, warning=FALSE}
# Purpose: This function scrapes lyrics from songlyrics.com for the billboard top 100 country songs 
# Input: Our songs data frame
# Output: A new column in the songs data frame with lyrics for every song
scrape_lyrics <- function(df) {
  lyrics <- character(nrow(df))  
  for (i in 1:nrow(df)) {
    url <- paste0("https://www.songlyrics.com/", df$Artist[i], "/", df$Title[i], "-lyrics/")
    # Tests for errors when getting URLs and makes sure code keeps running after an error occurs
    tryCatch({
      html <- read_html(url)
      raw_lyrics <- html_nodes(html, "#songLyricsDiv") %>% html_text() %>% as.character()
      lyrics[i] <- paste(raw_lyrics, collapse = " ")
    }, error = function(e) {
    })
  }
  df$lyrics <- lyrics  
  return(df)
}
# Apply function to our data frame
TopSongs3 <- scrape_lyrics(TopSongs2)
```

```{r, warning=FALSE}
###EVA#####
# Modifies song lyrics to match
TopSongs3$lyrics <- gsub("\n", " ", TopSongs3$lyrics)
TopSongs3$lyrics <- gsub("[,.()]", "", TopSongs3$lyrics)
TopSongs3$lyrics <- tolower(TopSongs3$lyrics)
# Remove rows with missing lyrics
TopSongs3 <- subset(TopSongs3, !(is.na(lyrics) | lyrics == ""))
TopSongs3 <- subset(TopSongs3, !grepl("we do not have the lyrics for", lyrics))


##JULIA###
#getting rid of duplicate songs
TopSongs3 <- TopSongs3[!duplicated(TopSongs3$Title), ]

#get rid of the dashes and make them spaces
TopSongs3$Title <- gsub("-", " ", TopSongs3$Title)
TopSongs3$Artist <- gsub("-", " ", TopSongs3$Artist)

#change title and artist to all lower case
TopSongs3$Title<-tolower(TopSongs3$Title)
TopSongs3$Artist<-tolower(TopSongs3$Artist)


#save it as a csv file to working directory
write.csv(TopSongs3, "TopCountry.csv", row.names = FALSE)

#call it to test that it works and reads it correctly
TopCountry<-read.csv("TopCountry.csv")


```

RAP CODE 
```{r, warning=FALSE}
urlfunctionRap <- function(year) {
  if (year >= 2007 && year <= 2023) {
      country_url <- paste0("https://en.wikipedia.org/wiki/List_of_number-one_R%26B/hip-hop_songs_of_", year, "_(U.S.)")
      html <- read_html(country_url)
      cast <- html_nodes(html, "th , .plainrowheaders td")
      html_text(cast, trim = TRUE) 
      tables <- html_table(html, fill = TRUE, header = TRUE)
      desired_table <- tables[[2]]
      desired_table <- desired_table[, -1]
      
  }else {
      country_url <- paste0("https://en.wikipedia.org/wiki/", year, "_in_hip_hop_music")
      html <- read_html(country_url)
      cast <- html_nodes(html, ".headerSort , .jquery-tablesorter td, .headerSort") 
      html_text(cast, trim = TRUE) 
      tables <- html_table(html, fill = TRUE, header = TRUE)
      if (year == 2000 || year >= 2002) {
        desired_table <- tables[[5]]
      }else{
        desired_table <- tables[[6]]
      }
  }
  

  colnames(desired_table) <- c("Title", "Artist")
    #name columns
  desired_table$Year <- year
     #add columns for year
  desired_table$genre <- "Rap" 
     #add column for genre
  desired_table <- unique(desired_table)

return(desired_table)
}
fun2 <- urlfunctionRap(1987)
TopRapSongs <- rbindlist(lapply(1987:2023, urlfunctionRap), fill = TRUE)
TopRapSongs <- TopRapSongs[,c(1,2,5,6), drop = FALSE]
TopRapSongs <- unique(TopRapSongs)
DFTopRapSongs <- as.data.frame(TopRapSongs)
filter_titles <- function(df) {
  df[grep("^\"", df$Title), ]
}

# Apply the function to TopRapSongs
DFTopRapSongs <- filter_titles(DFTopRapSongs)
DFTopRapSongs$Title<-gsub('"', '', DFTopRapSongs$Title)
DFTopRapSongs <- sapply(DFTopRapSongs, function(x) gsub(" ", "-", x))
DFTopRapSongs <- as.data.frame(DFTopRapSongs)
DFTopRapSongs$Title <- sub("-$", "", DFTopRapSongs$Title)
DFTopRapSongs$Title <- gsub("[,.?%()]", "", DFTopRapSongs$Title)
DFTopRapSongs$Artist <- gsub("[.']", "", DFTopRapSongs$Artist)
DFTopRapSongs$Artist <- sub("-and", "", DFTopRapSongs$Artist)

LyricsTopRapSongs3 <- scrape_lyrics(DFTopRapSongs)

# Modifies song lyrics to match
LyricsTopRapSongs3$lyrics <- gsub("\n", " ", LyricsTopRapSongs3$lyrics)
LyricsTopRapSongs3$lyrics <- gsub("[,.()]", "", LyricsTopRapSongs3$lyrics)
LyricsTopRapSongs3$lyrics <- tolower(LyricsTopRapSongs3$lyrics)
# Remove rows with missing lyrics
LyricsTopRapSongs3 <- subset(LyricsTopRapSongs3, !(is.na(lyrics) | lyrics == ""))
LyricsTopRapSongs3 <- subset(LyricsTopRapSongs3, !grepl("we do not have the lyrics for", lyrics))
# Remove dashes between title and artist
LyricsTopRapSongs3$Title<-gsub("-", " ", LyricsTopRapSongs3$Title)
LyricsTopRapSongs3$Artist<-gsub("-", " ", LyricsTopRapSongs3$Artist)

write.csv(LyricsTopRapSongs3, "TopRapSongs.csv", row.names = FALSE)
TopRapSongsCSV <-read.csv("TopRapSongs.csv")
```


## Measure of Repetitivness: Unqiue Words Ratio - Tessa
```{r, warning=FALSE}
# UNIQUE RATIO FUNCTION WITH GRAPH
# Purpose: To generate a ratio of unique words to total words within song lyrics for each year included in the data frame and create a ggplot of the resulting data.
# The function inputs: The input of this function is a data frame, which must have columns with "year" and "lyrics". It also take in graph_title which allows you to specifically name your graph.
# The function output: The function return a data frame with columns of year, total words, unique words, and unique ratio. The function will print the graph out showing a trend of unique word ratio over time.

generate_unique_ratios_graph <- function(song_df, graph_title) {

generate_unique_ratios <- function(song_df) {
  # make lyrics into single words using tidytext package
  token_lyrics <- song_df %>%
    unnest_tokens(words, lyrics) %>%
    mutate(Year = Year)  # include year data

  # Group by year and calculate unique words ratio
  unique_words_by_year <- token_lyrics %>%
    group_by(Year) %>%  # group lyrics by year
    summarise(total_words = n(), # find total words
              unique_words = n_distinct(words), # find unique words using dplyr (n_distincy)
              ratio = unique_words / total_words) # find ratio of unique words to total words

  return(unique_words_by_year)
}
# low ratio means songs are more repetitive
unique_words_ratios <- generate_unique_ratios(song_df) 

# find the overall unique words ratio to add to graph:
overall_unique_words_ratio <-mean(unique_words_ratios$ratio)

# find middle of years so the label is in the middle of the graph
x_midpoint <- median(unique_words_ratios$Year)

# graph unique words ratio over the years
unique_ratio_graph_by_year <-ggplot(unique_words_ratios, aes(x = Year, y = ratio)) +
  geom_line() +
  geom_hline(yintercept = overall_unique_words_ratio, color = "skyblue3") + #add an hline to show when the data is above and below average
  annotate("text", x = x_midpoint, y = overall_unique_words_ratio + 0.01, label = "Average Unique Words Ratio", color = "skyblue3" ) +  # add label to represent what hline means
  labs(title = graph_title, # can customize title
       x = "Year",
       y = "Unique Words Ratio") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) # center title

return(unique_ratio_graph_by_year)
}

Country_Unique_Ratio_Graph <-generate_unique_ratios_graph(TopCountry, "Unique Words Ratio of Top Country Songs Over Time")
Country_Unique_Ratio_Graph
HipHop_Unique_Ratio_Graph <-generate_unique_ratios_graph(TopRapSongsCSV, "Unique Words Ratio of Top Hip Hop Songs Over Time")
HipHop_Unique_Ratio_Graph

```

## Measure of Receptiveness: Title Repetition - Tessa and Julia
```{r, warning=FALSE}
# TITLE REPETITION FUNCTION WITH GRAPH INCLUDED
# Purpose: To find the number of times a song repeats its title within its own lyrics. Then add the frequency of repeats to the inputted data frame. Lastly it will provide a graph of average title repeats over time with a linear regression model to see if there is a linear relationship.
# The function inputs: The input of this function is a data frame, which must have columns with "Title", "Year", and "lyrics".
# The function output: The function returns the inputted data frame, along with a column called repeats. It will print out a graph showing average title repeats over time with a fitted linear regression model. It will also output some summary statistics of the fitted model.

generate_title_repetition_graph <- function(song_df, graph_title) {
  # Initialize empty column called repeats to hold frequency
  song_df$repeats <- numeric(nrow(song_df))
  
  # for each row in inputted data frame:
  for (i in 1:nrow(song_df)) {
    title <- tolower(song_df$Title[i])  # extract title
    lyrics <- tolower(song_df$lyrics[i]) # extract lyrics
    
    # sum number of times the title is in the lyrics
    title_count <- sum(gregexpr(title, lyrics)[[1]] > 0) # match string to another string and check if we get a result
    
    # add repeats count to the existing data frame
    song_df$repeats[i] <- title_count
  }
  
  #create table with average title repeats within each song per year
  ave_title_repeats_by_year <- song_df %>%
    group_by(Year) %>%
    summarize(AveTitleRepeats = mean(repeats))
  
  # plot data by year
  ave_title_repeats <-
    ggplot(ave_title_repeats_by_year, aes(x = Year, y = AveTitleRepeats)) +
    geom_point(size = 1.2) +
    geom_smooth(method = "lm", se = FALSE, color = "skyblue3") +
    labs(title = graph_title,
         x = "Year",
         y = "Mean Title Repeats Per Year") +
    theme_minimal() +
    scale_y_continuous(limits = c(0, NA), breaks = seq(0, max(
      ave_title_repeats_by_year$AveTitleRepeats
    ), by = 5)) + theme(plot.title = element_text(hjust = 0.5))
  
  print(ave_title_repeats)
  
  res2 <- lm(AveTitleRepeats ~ Year, ave_title_repeats_by_year)
  print(summary(res2))
  
}

Country_Title_Repetition <-generate_title_repetition_graph(TopCountry, "Average Title Repeats of Top Country Over Time")
HipHop_Title_Repetition <-generate_title_repetition_graph(TopRapSongsCSV, "Average Title Repeats of Top Hip Hop Over Time")

```


## Sophie
```{r, warning=FALSE}
alcohol <- c("whiskey", "moonshine", "beer", "wine", "tequila", "vodka", "jack daniels", "budlight", "coorslight", "busch", "alcohol", "rum", "gin", "brandy", "cognac", "schnapps", "absinthe", "champagne", "sake")
intimacy <- c("sexy", "hot", "sex", "attractive", "baby", "babe", "lover", "sweetheart", "passion", "desire", "romance", "affection", "intimacy", "seductive", "lust")
family <- c("mom", "mama", "granny", "marriage", "children", "marry", "wife", "husband", "dogs", "father", "daddy", "grandpa", "grandmother", "aunt", "uncle", "cousin", "siblings", "in-laws", "offspring")
drugs <- c("coke", "cocaine", "tabacco", "weed", "heroin", "methamphetamine", "LSD", "ecstasy", "prescription drugs", "opioids", "hallucinogens", "MDMA", "smoke", "smoking")
guns <- c("gun", "guns", "revolver", "shotgun", "rifle", "pistol", "firearm", "ammunition", "sniper", "handgun", "arsenal")
music <- c("melody", "rhythm", "harmony", "lyrics", "genre", "beat", "album", "artist", "band", "guitar")
sad <- c("heartbreak", "sorrow", "grief", "despair", "melancholy", "misery", "anguish", "heartache", "depression", "tears")
countylivin <- c("cowboy", "horse", "truck", "pickup", "road", "tea", "tractor", "barn", "ranch", "cattle", "hay", "pasture", "cowboy boots", "western", "yeehaw", "rodeo")
town <- c("small town", "hometown", "back home", "home", "village", "community", "neighborhood", "suburb", "township", "locality", "settlement")
swear <- c("hell", "damn", "fuck", "bitch", "bitch", "ass", "asshole", "bastard", "shit", "bloody", "hellfire", "motherfucker", "crap", "piss", "bollocks", "wanker", "bugger")
violence <- c("violence", "fight", "attack", "assault", "battle", "war", "weapon", "blood", "kill", "murder", "homicide", "gun", "knife", "bullet", "shot", "stab", "punch", "strangle", "choke", "brutal", "beating", "injure", "wound", "trauma", "hurt", "pain", "suffering", "death", "hit")

  alcohol_count <- 0
  intimacy_count <- 0
  family_count <- 0
  drugs_count <- 0
  guns_count <- 0
  music_count <- 0
  sad_count <- 0
  countylivin_count <- 0
  town_count <- 0
  swear_count <- 0
  violence_count <- 0
  
# Purpose:
# Input:
# Output:
ThemeGraph <- function(TopGenre, graph_title) {
# Loop through each row of the lyrics column in Topsongs2
for (lyric in TopGenre$lyrics) {
  # Check if any word from each vector is present in the lyrics
  if (any(grepl(paste(alcohol, collapse = "|"), lyric, ignore.case = TRUE))) {
    alcohol_count <- alcohol_count + 1
  }
  if (any(grepl(paste(intimacy, collapse = "|"), lyric, ignore.case = TRUE))) {
    intimacy_count <- intimacy_count + 1
  }
  if (any(grepl(paste(family, collapse = "|"), lyric, ignore.case = TRUE))) {
    family_count <- family_count + 1
  }
  if (any(grepl(paste(drugs, collapse = "|"), lyric, ignore.case = TRUE))) {
    drugs_count <- drugs_count + 1
  }
  if (any(grepl(paste(guns, collapse = "|"), lyric, ignore.case = TRUE))) {
    guns_count <- guns_count + 1
  }
  if (any(grepl(paste(music, collapse = "|"), lyric, ignore.case = TRUE))) {
    music_count <- music_count + 1
  }
  if (any(grepl(paste(sad, collapse = "|"), lyric, ignore.case = TRUE))) {
    sad_count <- sad_count + 1
  }
  if (any(grepl(paste(countylivin, collapse = "|"), lyric, ignore.case = TRUE))) {
    countylivin_count <- countylivin_count + 1
  }
  if (any(grepl(paste(town, collapse = "|"), lyric, ignore.case = TRUE))) {
    town_count <- town_count + 1
  }
  if (any(grepl(paste(swear, collapse = "|"), lyric, ignore.case = TRUE))) {
    swear_count <- swear_count + 1
  }
  if (any(grepl(paste(violence, collapse = "|"), lyric, ignore.case = TRUE))) {
    violence_count <- violence_count + 1
  }
}

# Create a data frame to store the counts
total_counts <- data.frame(
  vector = c("Alcohol", "Intimacy", "Family", "Drugs", "Guns", "Music", "Sad", "Country Living", "Town", "Swear", "Violence"),
  count = c(alcohol_count, intimacy_count, family_count, drugs_count, guns_count, music_count, sad_count, countylivin_count, town_count, swear_count, violence_count)
)

# Make counts into proportions so we can compare across genres
total_counts$proportion <- total_counts$count / sum(total_counts$count)

# Create a bar chart using ggplot with proportions
ggplot(total_counts, aes(x = vector, y = proportion)) +
  geom_bar(stat = "identity") +
  labs(title = graph_title, # title can be customized
       x = "Themes",
       y = "Proportion of Songs with Words in Themes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), #adjust axis
        plot.title = element_text(hjust = 0.5))
}

ThemeGraph(TopRapSongsCSV, "Proportions of Themes Found in Hip Hop Songs")
ThemeGraph(TopCountry, "Proportions of Themes Found in Country Songs")
```

